CREATE TABLE IF NOT EXISTS ARTIST (
    ARTIST_ID INTEGER PRIMARY KEY,
    ARTIST_NAME VARCHAR,
    ARTIST_THUMBNAIL VARCHAR,
    DATE_CREATED DATETIME,
    LAST_MODIFIED DATETIME
);

CREATE TABLE IF NOT EXISTS ARTIST_AUDIO_FILE (
    ARTIST_AUDIO_FILE_ID INTEGER PRIMARY KEY,
    ARTIST_ID INTEGER,
    AUDIO_FILE_ID INTEGER,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID), 
    FOREIGN KEY (AUDIO_FILE_ID) REFERENCES AUDIO_FILE(AUDIO_FILE_ID)
);