DROP TABLE IF EXISTS ARTIST; 
DROP TABLE IF EXISTS ARTIST_AUDIO_FILE; 
DROP TABLE IF EXISTS GENRE; 
DROP TABLE IF EXISTS GENRE_AUDIO_FILE; 
DROP TABLE IF EXISTS PLAYLIST; 
DROP TABLE IF EXISTS PLAYLIST_AUDIO_FILE; 
