CREATE TABLE IF NOT EXISTS POMODORO_SESSION (
    SESSION_ID INTEGER PRIMARY KEY,
    SESSION_NAME VARCHAR,
    DURATION INTEGER,
    DURATION_LIMIT INTEGER,
    SHORT_BREAK INTEGER,
    LONG_BREAK INTEGER,
    DATE_CREATED DATETIME,
    LAST_MODIFIED DATETIME
);

CREATE TABLE IF NOT EXISTS POMODORO_AUDIO_FILE (
    POMODORO_AUDIO_FILE_ID INTEGER PRIMARY KEY,
    SESSION_ID INTEGER,
    AUDIO_FILE_ID INTEGER,
    FOREIGN KEY (SESSION_ID) REFERENCES POMODORO_SESSION(SESSION_ID), 
    FOREIGN KEY (AUDIO_FILE_ID) REFERENCES AUDIO_FILE(AUDIO_FILE_ID)
);