CREATE TABLE IF NOT EXISTS AUDIO_FILE (
    AUDIO_FILE_ID INTEGER PRIMARY KEY,
    FILE_NAME VARCHAR,
    FILE_PATH VARCHAR,
    THUMBNAIL VARCHAR,
    DURATION VARCHAR,
    PLAYS INTEGER,
    SAMPLE_RATE VARCHAR,
    DATE_CREATED DATETIME,
    LAST_MODIFIED DATETIME
);