CREATE TABLE IF NOT EXISTS PLAYLIST (
    PLAYLIST_ID INTEGER PRIMARY KEY,
    PLAYLIST_NAME VARCHAR,
    DATE_CREATED DATETIME,
    LAST_MODIFIED DATETIME
);

CREATE TABLE IF NOT EXISTS PLAYLIST_AUDIO_FILE (
    PLAYLIST_AUDIO_FILE_ID INTEGER PRIMARY KEY,
    PLAYLIST_ID INTEGER,
    AUDIO_FILE_ID INTEGER,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(PLAYLIST_ID), 
    FOREIGN KEY (AUDIO_FILE_ID) REFERENCES AUDIO_FILE(AUDIO_FILE_ID)
);