CREATE TABLE IF NOT EXISTS AUDIO_FILE (
    AUDIO_FILE_ID INTEGER PRIMARY KEY,
    AUDIO_FILE_NAME VARCHAR,
    FILE_PATH VARCHAR,
    DURATION VARCHAR,
    DATE_CREATED DATETIME,
    LAST_MODIFIED DATETIME,
    PLAYS INTEGER,
    SAMPLE_RATE VARCHAR
);