name: "Data Sources"
description: "Configuration for all data sources on DTunes"
base_path: "adms/sources"
sources:
  - source_name: "YouTube"
    url: "https://youtube.com"
    api_key: "None"
    description: "Most popular video streaming site by Google"
    storage_location: "adms/sources/youtube"
    file_types:
      - "mp4"
      - "mp3"
      - "wav"

  - source_name: "SoundCloud"
    url: "https://soundcloud.com"
    api_key: "None"
    description: "Free music site for independent artists"
    storage_location: "adms/sources/soundcloud"
    file_types:
      - "mp4"
      - "mp3"
      - "wav"
      - "Flacc"