name: DTunes

on:
  pull_request:
    branches: [ "main" ]

jobs:

  dtunes_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --color always
        working-directory: src-tauri/

      - name: Test
        run: cargo test -- color always --test-threads=1
