name: DTunes

on:
  pull_request:
    branches: [ "main" ]

jobs:

  dtunes_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update apt cache
        run: sudo apt-get update

      - name: Install GTK
        run: sudo apt-get install libwebkit2gtk-4.1-dev
        working-directory: src-tauri/

      - name: Test
        run: cargo test -- color always
        working-directory: src-tauri/

  publish-site: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: Install Dependencies
        run: npm install
        working-directory: dtunes-site/

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: dtunes-site/

