name: DTunes CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: cargo test
 
  windows-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: cargo test
 
  mac-os-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: cargo test
