name: Build App


on:
  pull_request:
    branches: [ "main" ]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install GTK
        run: sudo apt-get install libwebkit2gtk-4.1-dev
        working-directory: src-tauri/

      - name: Build Tauri App
        run: tauri build

  mac-os:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      # - name: Install GTK
      #   run: brew install gtk+3
      #   working-directory: src-tauri/

      # Build the Tauri app
      - name: Build Tauri App
        run: tauri build

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri App
        run: tauri build
